apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - platform.yaml
  - data.yaml
  - migration-job.yaml
  - seed-job.yaml
  - applications.yaml
  - network-policies.yaml
  - backup.yaml
  - traefik-middleware.yaml
