apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-companion-http
  namespace: anime-companion
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: anime-companion-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: animecompanion.icu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-companion-https
  namespace: anime-companion
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - animecompanion.icu
      secretName: animecompanion-icu-production-tls
  rules:
    - host: animecompanion.icu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
